# Thruster Manager Configuration for 8-thruster drone
tam:
  # Thruster identification - use joint names from URDF
  thrusters: ['thruster_joint_1', 'thruster_joint_2', 'thruster_joint_3', 'thruster_joint_4', 
              'thruster_joint_5', 'thruster_joint_6', 'thruster_joint_7', 'thruster_joint_8']
  
  # Thrust constraints (adjust based on your motor specs)
  min_thrust: -50.0    # Negative thrust capability
  max_thrust: 50.0     # Maximum positive thrust
  deadzone: 0.5        # Small deadzone to avoid jitter
  continuity: 0.1      # Weight on thrust continuity
  
  # Use TF for dynamic allocation matrix computation
  use_tf: true
  use_gz_plugin: false

# Control frame (where wrench commands are expressed)
control_frame: "base_link"

# Thruster Manager Node I/O settings
publish_joint_state: false      # Don't use JointState output
publish_gz_command: true        # Use individual Float64 topics for Gazebo
subscribe_stamped: true         # Accept WrenchStamped messages
