- ros_topic_name: "/clock"
  gz_topic_name: "/world/default/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/rotors/command/motor_speed"
  gz_topic_name: "/drone_frame/rotors/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "ignition.msgs.Actuators"
  direction: ROS_TO_GZ
- ros_topic_name: "/thruster_1/cmd"
  gz_topic_name: "/drone_frame/thruster_1/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/thruster_2/cmd"
  gz_topic_name: "/drone_frame/thruster_2/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/thruster_3/cmd"
  gz_topic_name: "/drone_frame/thruster_3/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/thruster_4/cmd"
  gz_topic_name: "/drone_frame/thruster_4/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/thruster_5/cmd"
  gz_topic_name: "/drone_frame/thruster_5/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/thruster_6/cmd"
  gz_topic_name: "/drone_frame/thruster_6/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/thruster_7/cmd"
  gz_topic_name: "/drone_frame/thruster_7/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/thruster_8/cmd"
  gz_topic_name: "/drone_frame/thruster_8/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS